#!/bin/bash

# Author: Fabio J. Matos Nieves
# Date Created: 07/8/2021
# Last Modified: 07/8/2021

# Description
# This script selects or prompts you to select a color script to run in your terminal regardless of distrobution

# Usage
# Usage: ./colorscripts.sh [-l] [-r] [-e <NAME>] [-s]

shellcolorscriptdir=$HOME/.colorscripts

usage()
{
    echo "Usage: $0 [-l] [-r] [-e <NAME>] [-s]" ; echo "-l Lists all currently available color scripts" ; echo "-r Executes a random color script"; echo "-e <NAME> Executes the given color script" ; echo "-s Displays a menu of the available color scripts and prompts the user to chose one" 1>&2; exit 1;

}

if [ ! -d "$HOME/.colorscripts"  ]; then
    mkdir "$HOME/.colorscripts"
    echo "Place your shell color scripts in $shellcolorscriptdir"
    exit 1
fi

chmod 755 -R "$shellcolorscriptdir"

readarray -t scs < <(ls $shellcolorscriptdir)

while getopts "lre:s" opt; do
        case "${opt}" in
            l)
               ls "$shellcolorscriptdir"
               exit 0
               ;;
            r)
               colorscriptwc=$(ls "$shellcolorscriptdir" | wc -l)
               randindex=$(($RANDOM%$colorscriptwc))
               cd "$shellcolorscriptdir"
               ./"${scs[$randindex]}"
               echo ""
               exit 0
               ;;
            e)
               cd "$shellcolorscriptdir"
               if [ -z "$(echo "${scs[@]}" | grep "${OPTARG}")" ]; then
                   echo "Script doesn't exist"
                   usage

               fi
               ./"${OPTARG}"
               echo ""
               exit 0
               ;;
            s)
               PS3="Which script would you like to execute: "
               select script in ${scs[@]}; do
                   break
               done
               echo ""
               cd "$shellcolorscriptdir"
               ./"$script"
               echo ""
               exit 0
               ;;
            *)
               usage
               ;;
    esac
done


if [ -z "$1" ] || [ -z "$e" ]; then
    usage
fi

# Sources
# Color scripts: Derek Taylor (https://gitlab.com/dwt1/shell-color-scripts)
