#!/bin/bash

# Author: Fabio J. Matos Nieves
# Date Created: 07/8/2021
# Last Modified: 08/8/2021

# Description
# This script selects or prompts you to select a color script to run in your terminal regardless of distrobution

# Usage
# Usage: ./colorscripts [-l] [-r] [-e <NAME>] [-s]

sudoneeded=0

if [ -f /etc/colorscripts.conf ]; then
    shellcolorscriptdir=/usr/share/colorscripts
    sudoneeded=1
else
    shellcolorscriptdir=$HOME/.colorscripts
fi

usage()
{
    echo "Usage: $0 [-l] [-r] [-e <NAME>] [-s]" ; echo "-l Lists all currently available color scripts" ; echo "-r Executes a random color script"; echo "-e <NAME> Executes the given color script" ; echo "-s Displays a menu of the available color scripts and prompts the user to chose one" ; echo "-b Displays all unblacklisted color scripts and prompts the user to select a color script to blacklist"  ; echo "-u Displays all blacklisted color scripts and prompts the user to select a color script to unblacklist" 1>&2; exit 1;

}

if [ ! -d "$shellcolorscriptdir" ]; then
    mkdir "$HOME/.colorscripts"
    echo "Place your shell color scripts in $shellcolorscriptdir"
    exit 1
fi

readarray -t scs < <(ls -Iblacklist $shellcolorscriptdir)

while getopts "lresbu" opt; do
        case "${opt}" in
            l)
               n=1
               for script in "${scs[@]}";
               do
                   echo "$n $script"
                   n=$(( $n+1 ))
               done
               exit 0
               ;;
            r)
               colorscriptwc=$(ls -Iblacklist "$shellcolorscriptdir" | wc -l)
               randindex=$(($RANDOM%$colorscriptwc))
               cd "$shellcolorscriptdir"
               ./"${scs[$randindex]}"
               exit 0
               ;;
            e)
               cd "$shellcolorscriptdir"
               if [ -z "$(echo "${scs[@]}" | grep "${OPTARG}")" ]; then
                   echo "Script doesn't exist"
                   usage

               fi
               ./"${OPTARG}"
               exit 0
               ;;
            s)
               PS3="Which script would you like to execute: "
               select script in ${scs[@]}; do
                   break
               done
               echo ""
               cd "$shellcolorscriptdir"
               ./"$script"
               exit 0
               ;;
            b)
               PS3="Which script would you like to blacklist: "
               select script in ${scs[@]}; do
                   break
               done
               if [ $sudoneeded -eq 1 ]; then
                   sudo mv "$shellcolorscriptdir/$script" "$shellcolorscriptdir/blacklist/"
               else
                   cd "$shellcolorscriptdir"
                   mv $script blacklist
               fi
               exit 0
               ;;
            u)
               PS3="Which script would you like to unblacklist: "
               readarray -t uscs < <(ls "$shellcolorscriptdir/blacklist")
               if [ "${#uscs[@]}" -gt 0 ]; then
                  select script in "${uscs[@]}";
                  do
                      break
                  done
                  if [ $sudoneeded -eq 1 ]; then
                      sudo mv "$shellcolorscriptdir/blacklist/$script" "$shellcolorscriptdir"
                  else
                      cd "$shellcolorscriptdir"
                      mv "blacklist/$script" "$shellcolorscriptdir"
                  fi
                  exit 0
               else
                   echo "There are no blacklisted scripts"
                   exit 0
               fi
               ;;
            h)
               usage
               ;;
            *)
               usage
               ;;
    esac
done

if [ -z "$1" ] || [ -z "$e" ]; then
    usage
fi

# Sources
# Color scripts: Derek Taylor (https://gitlab.com/dwt1/shell-color-scripts)
